apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
{{ include "webapp.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "webapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.container.ports | nindent 12}}
          {{- if .Values.container.livenessProbe }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.container.livenessProbe.delaySeconds }}
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            {{- if eq "http" .Values.container.livenessProbe.type }}
            httpGet:
            {{- else if eq "tcp" .Values.container.livenessProbe.type }}
            tcpSocket:
            {{- else }}
            exec:
            {{- end }}
              {{- toYaml .Values.container.livenessProbe.probe | nindent 14 }}
          {{- end }}
          {{- if .Values.container.readinessProbe }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.container.readinessProbe.delaySeconds }}
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            {{- if eq "http" .Values.container.readinessProbe.type }}
            httpGet:
            {{- else if eq "tcp" .Values.container.readinessProbe.type }}
            tcpSocket:
            {{- else }}
            exec:
            {{- end }}
              {{- toYaml .Values.container.readinessProbe.probe | nindent 14 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
