{{- $g := . -}}
{{- range .Values.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "webapp.fullname" $g }}-{{ .name }}
  labels:
{{ include "webapp.labels" $g | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx{{ if .inner }}-internal{{ end }}
    {{- if .grpc }}
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    {{- end }}
spec:
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ include "webapp.fullname" $g }}-{{ .serviceName }}
              servicePort: {{ .servicePort }}
        {{- end }}
    {{- end }}
{{- end }}
